### ISSUE TITLE
Error during integration setup since Homeassistant 2023.4.0

### ISSUE THREAD

**Issue by aturri** [sdesalve/zcsazzurro#24]
Hi, 
since **Homeassistant 2023.4.0**, this integration is no longer working. It is not possible to setup the sensor platform and this is the log I can see:

Logger: homeassistant.components.sensor
Source: components/rest/data.py:65
Integration: Sensore (documentation, issues)
First occurred: 08:17:26 (1 occurrences)
Last logged: 08:17:26

Error while setting up zcsazzurro platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/zcsazzurro/sensor.py", line 85, in async_setup_platform
    await rest.async_update()
  File "/usr/src/homeassistant/homeassistant/components/rest/data.py", line 65, in async_update
    response = await self._async_client.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1520, in request
    request = self.build_request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 360, in build_request
    return Request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 339, in __init__
    headers, stream = encode_request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_content.py", line 209, in encode_request
    return encode_content(content)
  File "/usr/local/lib/python3.10/site-packages/httpx/_content.py", line 134, in encode_content
    raise TypeError(f"Unexpected type for 'content', {type(content)!r}")
TypeError: Unexpected type for 'content', <class 'bool'>

**Comment by aturri** [comment]
I've found that RestData constructor requires an additional parameter for encoding:

`rest = RestData(hass, method, _ENDPOINT, 'utf8' auth, headers, None, string_payload, verify_ssl, timeout)`

In this way it seems to work

**Comment by Corrado56** [comment]
> I've found that RestData constructor requires an additional parameter for encoding:
> 
> `rest = RestData(hass, method, _ENDPOINT, 'utf8', auth, headers, None, string_payload, verify_ssl, timeout)`
> 
> In this way it seems to work

Confirmed.  adding new 'utf8' parameter in restdata call it works again
the line is in custom_components/zcsazzurro/sensor.py line 84

**Comment by sdesalve** [comment]
Many thanks
